# Generated by Django 2.1.3 on 2018-11-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181109_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='item',
            new_name='text',
        ),
    ]
